modLoader="javafml" 
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]] 
   modId="${mod_id}" 
   version="${mod_version}" 
   displayName="${mod_name}" 
   authors="${mod_authors}" #optional
   logoFile="logo.png"
   description='''${mod_description}'''
   credits="Forge, Registrate, Jei, Create, Farmer's Delight, Create Crafts & Addition, Cultural Delight"

[[dependencies.${mod_id}]] #optional
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="create"
   mandatory=true
   versionRange="[6.0.7,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="farmersdelight"
   mandatory=true
   versionRange="[1.2.9,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="create_central_kitchen"
   mandatory=false
   versionRange="[1.3.12,)"
   ordering="NONE"
   side="BOTH"
