modLoader = "javafml"

loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
issueTrackerURL = "https://github.com/Neve133/RATATOUILLE/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/create-ratatouille"
logoFile = "logo.png"
authors = "${mod_authors}"
description='''${mod_description}'''
credits="Forge, Registrate, Jei, Create, Farmer's Delight, Create Crafts & Addition, Cultural Delight"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.2.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create_central_kitchen"
    type="optional"
    versionRange="[2.1.3,)"
    ordering="NONE"
    side="BOTH"
